### ISSUE TITLE
Make UI more user friendly

### ISSUE THREAD

**Issue by joshbaird** [joshbaird/MoistureSensingSprinkler#2]
Need to "pretty" up the UI.
Need inputs for on and off values for: moisture, light, temp, time, maybe chance of rain?

Anything else?

**Comment by bdcannon** [comment]
Maybe a "survey" widget. A small widget to show at the moment conditions. This would require additional logic and a period of polling.

**Comment by joshbaird** [comment]
see #1 for the JSON struct. we need fields for all those.
Some cool widgets and sliders and pickers would be cool. Flashy is nice.

**Comment by HarderBetterFasterStronger** [comment]
Not sure how the time is being stored but I want to store as Date Object for db... I was thinking Unix time first, but still have to investigate best way..

As for survey widget, was looking in to geolocation like http://leafletjs.com/ or something for the GUI side of things.

**Comment by bdcannon** [comment]
I was planning to store the date as the formatted string you can get from
the js object. It's pretty much a serialization and you can instantiate the
object just by passing the string into the contructor.

**Comment by bdcannon** [comment]
And by object I mean the js Date () object

**Comment by HarderBetterFasterStronger** [comment]
serial dating? this is getting serious, not sure if ready for this kind of commitment

but okay, do what you gotta do

**Comment by bdcannon** [comment]
Serialized as in just the object in text form like this "March 15 2015
PST...".  You get it from the date object like date.toStringFormatWhatever
() Then you can reinstantiate the object with new Date ("March 15 2015
PST...");

**Comment by joshbaird** [comment]
I like epoch personally. it makes my job easier when comparing. I can just compare them as ints.
epoch/unix are for computers, dates and times are for humans. I agree that when looking at the raw DB epoch or unix don't make a lot of sense. but whoever uses them can easily convert to a date object. Another nice thing about epoch-unix is that they don't suffer from locality issues (here we do MM/DD/YYYY others do DD/MM/YYYY and who knows what else...) Just some thoughts.
I am OK either way. if its a date string that's cool I just need to know the format for the python script.

**Comment by bdcannon** [comment]
+1 Locality issues. Epoch it is. The JS Date object handles creation and serialization with in reference to the epoch

**Comment by bdcannon** [comment]
Can we agree this is resolved for the moment. Changes or problem with the UI should be created in a new issue thread.

**Comment by joshbaird** [comment]
Sounds good to me. Any changes should probably be more specific anyways.
