### ISSUE TITLE
Add Route for Updating Existing Sensor

### ISSUE THREAD

**Issue by bdcannon** [joshbaird/MoistureSensingSprinkler#3]
Right now the add sensor route allows for duplicates. 
- Possibly check for duplicate entries based on some type of unique ID for each sensor and overwrite the old data or prompt the user with the current data for the sensor. 
- This should make data history for the sensor invalid (depending on what field was changed)

**Comment by joshbaird** [comment]
I will work on this now with the latest JSON object.

**Comment by joshbaird** [comment]
Needs testing but should be implemented. Added updatesensor. maps based on sensorId field. Also changed addsensor to check sensorId first and update if it already exists.

**Comment by joshbaird** [comment]
Fixed and tested.
