### ISSUE TITLE
Whole bunch of 404's for images.

### ISSUE THREAD

**Issue by joshbaird** [joshbaird/MoistureSensingSprinkler#7]
@mrfinks I am getting a lot of 404's when loading the page. I think a bunch of images are missing. maybe forgot to add to the repo?
![screen shot 2015-04-20 at 8 28 22 pm](https://cloud.githubusercontent.com/assets/5050145/7245208/ed27c908-e79b-11e4-8c43-7183378c4ee2.png)

**Comment by HarderBetterFasterStronger** [comment]
done in commit: 
e706a8e1de0a0a3164b9e6c047f95238af988e11

New favicon in public/
