### ISSUE TITLE
Fix README.MD

### ISSUE THREAD

**Issue by joshbaird** [joshbaird/MoistureSensingSprinkler#8]
Need to fix the README.MD to be more of a guide on how to take this repo and make it run. not really a document of how we made this. Thoughts?
Maybe take whats in the README.MD and move it to the wiki?

**Comment by bdcannon** [comment]
:+1: on the wiki. I kind of think that the readme should be like basic info and how to get stuff up and running. I think the documentation or instructions for how to do things should be moved to the wiki.

**Comment by joshbaird** [comment]
Ok I moved the current contents of README.MD to the wiki. I will update the README.MD now. Feel free to add to it.

**Comment by joshbaird** [comment]
setting as closed
